# stocks.py
import requests
import pandas as pd
import io
import streamlit as st

@st.cache_data(ttl=86400)
def get_live_nse_universe():
    """Direct exchange endpoint parsing via strict string-stripping protocols"""
    nse_url = "https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv"
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    }
    
    try:
        session = requests.Session()
        session.headers.update(headers)
        response = session.get(nse_url, timeout=15)
        
        if response.status_code == 200:
            csv_data = io.StringIO(response.text)
            df = pd.read_csv(csv_data)
            
            # 🔥 CRITICAL FIX: Strip all invisible leading/trailing whitespaces
            df.columns = df.columns.str.strip()
            df['SERIES'] = df['SERIES'].astype(str).str.strip()
            
            # Filter strictly for active rolling Equity Series
            df_eq = df[df['SERIES'] == 'EQ']
            
            symbols = df_eq['SYMBOL'].dropna().astype(str).str.strip().tolist()
            if len(symbols) > 100:
                return symbols
    except:
        pass

    # Dynamic Institutional Backup Watchlist if exchange network throws timeout
    return [
            "TIPSINDLTD", "WAAREERTL", "SWARAJENG", "INGERRAND", "TATAMOTORS", "RELIANCE", "INFY", "SHILCHTECH", "CDSL", "HAL",
    "TCS", "HDFCBANK", "ICICIBANK", "BHARTIARTL", "SBIN", "LICI", "ITC", "HINDUNILVR", "LT", "BAJFINANCE",
    "HCLTECH", "MARUTI", "SUNPHARMA", "ADANIENT", "KOTAKBANK", "TITAN", "AXISBANK", "ULTRACEMCO", "NTPC", "ONGC",
    "POWERGRID", "ASIANPAINT", "COALINDIA", "BAJAJFINSV", "M&M", "JSWSTEEL", "JIOFIN", "ADANIPORTS", "IRFC", "BPCL",
    "BAJAJ-AUTO", "EICHERMOT", "HINDALCO", "GRASIM", "NESTLEIND", "TECHM", "INDUSINDBK", "CIPLA", "TATASTEEL", "SBILIFE",
    "BRITANNIA", "HDFCLIFE", "ADANIGREEN", "ADANITRANS", "WIPRO", "LTIM", "DIVISLAB", "TATACONSUM", "BAJAJHLDNG", "DRREDDY",
    "APOLLOHOSP", "VBL", "BEL", "BCHANDRA", "SHRIRAMFIN", "DLF", "VBL", "CHOLAFIN", "GAIL", "PNB",
    "IOC", "ZOMATO", "TREND", "POLYCAB", "LODHA", "UNIONBANK", "BOB", "CANBK", "IDBI", "CUMMINSIND",
    "AUBANK", "HAVELLS", "PIDILITIND", "SIEMENS", "ABB", "TRENTPHARM", "MANKIND", "OBEROIRLTY", "PHOENIXLTD", "PRESTIGE",
    "MAXHEALTH", "LUPIN", "AUROPHARMA", "ALKEM", "PEL", "MUTHOOTFIN", "REMAN", "PATANJALI", "DIXON", "KALYANKJIL",
    "OFSS", "PERSISTENT", "KPITTECH", "COFORGE", "LTTS", "MPHASIS", "TATAELXSI", "CYIENT", "SONACOMS", "BHEL",
    "REC", "PFC", "HUDCO", "IREDA", "RVNL", "IRCON", "MAHABANK", "CENTRALBK", "IOB", "UCOBANK",
    "ASHOKLEY", "BALKRISIND", "MRF", "APOLLOTYRE", "CEATLTD", "JKTYRE", "EXIDEIND", "AMARAJABAT", "SONATSOFTW", "ZENSARTECH",
    "AMBUJACEM", "ACC", "DALBHARAT", "JKCEMENT", "RAMCOCEM", "HEIDELBERG", "INDIACEM", "PRSMJOHNSN", "VOLTAS", "BLUESTARCO",
    "HAVELS", "CROMPTON", "ORIENTELEC", "BAJAJELEC", "KEI", "RRKABEL", "FINCABLES", "BOSCHLTD", "UNO MINDA", "ENDURANCE",
    "SUPREMEIND", "ASTRAL", "FINPIPE", "ASHIRVAD", "JINDALSTEL", "SAIL", "NMDC", "KIOCL", "MOIL", "GPIL",
    "GLENMARK", "ZYDUSLIFE", "IPCALAB", "BIOCON", "LAURUSLABS", "GRANULES", "NATCOPHARM", "MARKSANS", "ERIS", "JBCHEPHARM",
    "COROMANDEL", "PIIND", "UPL", "SUMICHEM", "DEEPAK放", "SRF", "AARTIIND", "ATUL", "GNFC", "GSFC",
    "PAGEIND", "BATAINDIA", "RELAXO", "METROBRAND", "CAMPUS", "KEALTD", "ABFRL", "RAYMOND", "ARVIND", "WELSPUNIND",
    "SOBHA", "BRIGADE", "GODREJPROP", "PHOENIXLTD", "MAHLIFE", "SUNTECK", "KOLTEPATIL", "PURVA", "DBREALTY", "ASHIANA",
    "GODREJCP", "MARICO", "DABUR", "COLPAL", "BRITANNIA", "TATACONSUM", "BALRAMCHIN", "TRIVENI", "EIDPARRY", "RENUKA",
    "IRCTC", "INDIGO", "CONCOR", "GATEWAY", "VRLLOG", "MAHLOG", "BLUEDART", "DELHIVERY", "ALLCARGO", "TCI",
    "BSE", "MCX", "CDSL", "CAMS", "KFINTECH", "IEX", "ANGELONE", "MOTILALOFS", "GEOJITFSL", "5PAISA",
    "NYKAA", "PAYTM", "POLICYBZR", "DELHIVERY", "MAPMYINDIA", "RATEGAIN", "CEINFO", "AWFIS", "DATAPATTERNS", "MTARTECH",
    "MAZDOCK", "GRSE", "COCHINSHIP", "BDL", "ZENTECH", "ASTRON", "PARAS", "DCXTECH", "IDEAFORGE", "ECIL",
    "NHPC", "SJVN", "NEEPCO", "THANGAMAYL", "TITAN", "PCJEWELLER", "SENCO", "JOYALUKKAS", "TBZ", "RBZJEWEL",
    "EXICOM", "SERVOTECH", "KPIREEN", "GENSOL", "ORIENTGREEN", "BORORENEW", "SWELECT", "WEBELSOLAR", "UJAAS", "SUZLON",
    "NH", "MEDANTA", "APOLLOHOSP", "FORTIS", "MAXHEALTH", "ASTERDM", "SHALBY", "YATHARTH", "GLOBAL", "KOVAL",
    "TATACOMM", "HFCL", "ITI", "TEJASNET", "STERTOOLS", "ROLEXRINGS", "TIMKEN", "SKFINDIA", "SCHAEFFLER", "BEARING",
    "JSWENERGY", "CESC", "TORNTPOWER", "TATAPOWER", "RELIANCEPOWER", "JPPOWER", "BFUTIL", "RATTANINDIA", "GIPCL", "APEX",
    "JUBLFOOD", "DEVYANI", "WESTLIFE", "RESTAURANT", "BURGERKING", "SAPPHIRE", "SPECIALITY", "BARBEQUE", "COFFEE", "CAFE",
    "SUNTV", "ZEEL", "PVRINOX", "NETWORK18", "TV18BRDCST", "NDTV", "SAREGAMA", "TIPSINDLTD", "ENIL", "MUSIC",
    "TRIDENT", "ALOKINDS", "SUTLEJTEX", "NAHARIND", "NITINSPIN", "RSWM", "SANGAMIND", "VARDHMNTP", "FILATEX", "PASUPATI",
    "NCC", "HFCL", "JINDALSAW", "WELCORP", "MAHSEAMLES", "ISMTLTD", "TATASTEELASM", "RATNAMANI", "VENUSPIPES", "GOODLUCK",
    "EIHOTEL", "TAJGVK", "INDHOTEL", "CHALET", "LEMON TREE", "ROYALORCH", "SAYAJIHOTL", "KAMATH", "BYKE", "ADITI",
    "RADICO", "TI", "SULA", "SOMDIST", "GMBREW", "GLOBUSSPR", "ASAL", "JAGATJIT", "TILAK", "REPRO",
    "PVR", "INOX", "CINEVISTA", "EROSMEDIA", "KSERASERA", "PRIME", "GVFILM", "RAJTAN", "RADAAN", "CREATIVEYE",
    "CEATLTD", "JKTYRE", "APOLLOTYRE", "MRF", "GOODYEAR", "MODIRUBBER", "TVSCHREQL", "BALKRISIND", "KRISHANA", "DUNLOP",
    "SWSOLAR", "STERLINWIL", "ENGINEERSIN", "TECHNOE", "GEPIL", "BGRENERGY", "ALSTOMT&D", "VOLTAMP", "TRANSFORM", "IMPAL",
    "VGUARD", "BAJAJELEC", "CROMPTON", "ORIENTELEC", "HAVELLS", "POLYCAB", "KEI", "UNIVERSAL", "COROMANDEL", "DEEPAK",
    "CASTROLIND", "GULFCOILOIL", "TIDEWATER", "SAVERA", "GPIL", "JINDALSTEL", "SAIL", "TATASTEEL", "JSWSTEEL", "SHYAMMETL",
    "AETHER", "ANUPAMRAS", "TATACHEM", "GHCL", "DCW", "SUDARSCHEM", "VIDHIING", "BODALCHEM", "KIRIIND", "BHAGERIA",
    "JKPAPER", "WESTCOAST", "ANDHRAPAP", "SESAPAPER", "TNPL", "ORIENTPPR", "STARPAPER", "EMAMIPAP", "SESHAPAPER", "RUCHI",
    "CENTURYPLY", "GREENPLY", "RUSHIL", "STYLAM", "GREENPANEL", "ARCHIDPLY", "PLYWOOD", "TIMBER", "WOOD", "BOARDS",
    "KAJARIACER", "SOMANYCERA", "ORIENTBELL", "EXXARO", "NITCO", "AGL", "CERAMIC", "TILES", "SANWRE", "VITRA",
    "SUPREMEIND", "ASTRAL", "PRINCEPIPE", "FINPIPE", "JAINIRRIG", "RESPONIND", "KISAN", "PLASTBLENDS", "XPROINDIA", "KINGFA"
]

# Export clean assignment list to system layout
SCREENER_WATCHLIST = get_live_nse_universe()


