
public_gsheets_url = "https://docs.google.com/spreadsheets/d/1ld54OCt-mfc5qGCGdFmCXXrZeTHPLBWWL7eG0cxSRlU/edit"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ld54OCt-mfc5qGCGdFmCXXrZeTHPLBWWL7eG0cxSRlU/edit"
type = "gsheets"
